name = "ebbinghaus-lab-app"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ebbinghaus-db"
database_id = "bb23a795-14fc-4f3b-ac3b-80df3ec58169"
