name = "ebbinghaus-lab-app"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ebbinghaus-db"
database_id = "ebbinghaus-d1-local-id"

[triggers]
crons = ["0 0 * * *"]
