name = "ebbinghaus-lab-app"
pages_build_output_dir = "./public"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "ebbinghaus-db"
database_id = "ebbinghaus-d1-local-id"

[triggers]
crons = ["0 0 * * *"]
